feat: add likes
splincode/java-filmorate pull request #2
Opened 2022-08-22 21:46 UTC by splincode

2022-08-28 19:36 UTC, Frilock requested changes
В целом вопросов нет. 
Единственное, на мой взгляд, версии библиотек правильнее писать в properties, потому что pom файлы бывают нереально больших размеров и бегать по файлику искать где же там версию обновить становится не очень удобно.
Еще не очень понял, почему конструкторы классов не делаете публичными?

2022-08-28 19:36 UTC, Frilock commented on pom.xml
> +			<version>0.1.2</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${simple-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2022-08-28 19:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmsController.java
> +    FilmsController(FilmsService filmsService) {
а чего public модификатор не ставите?

2022-08-28 19:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmsService.java
> +    FilmsService(
Можно на RequairedArgsConstructor заменить от lombok, чтобы простыню не писать такую

2022-08-28 19:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmsService.java
> +                .stream()
.stream можно на той же строке писать, а потом уже остальные операции переносить, но это вкусовщина конечно

2022-08-29 19:28 UTC, splincode commented on pom.xml
> +			<version>0.1.2</version>
fixed

2022-08-29 19:28 UTC, splincode commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmsController.java
> +    FilmsController(FilmsService filmsService) {
fixed

2022-08-29 19:28 UTC, splincode commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmsService.java
> +    FilmsService(
fixed

2022-08-29 19:28 UTC, splincode commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmsService.java
> +                .stream()
fixed

2022-08-30 07:32 UTC, Frilock approved these changes
Принято

2024-07-23 11:59 UTC, merged